### ISSUE TITLE
document behavior when module is not installed

### ISSUE THREAD

**Issue by j0057** [j0057/setuptools-version-command#4]
Update documentation for when module is not installed. 

Could use `setup_requires` or few lines of code in the `setup.py`.

**Comment by tuukkamustonen** [comment]
Something to include/consider:

Special effort is required only when package is source distribution (`.tar.gz`). Binary distributions ('.egg`, `.whl`) don't require anything, as version identifier is already hard-coded into them.

While `setup_requires` works with Internet connection, it becomes problematic without one:

In my scenario, I don't have access to pypi in deployment server so `setup_requires` would fail. However, it is possible to embed `setuptools-version-command` package as an *egg* inside `.tar.gz` package. In `setuptools<7.0`, it must go the root of the package. In `setuptools>=7.0`, it must go under `.eggs` directory inside the package.

Also, it seems the embedded `setup_requires` packages need to be eggs, `.tar.gz` will not work. Thus, it could be beneficial if `setuptools-version-command` was published also as an egg to pypi. Of course, it would be even nicer if package simply automated bundling the requirement inside source distributions.
